server:
  port: 8888

#spring.profiles.active: native

spring:
  cloud:
    config:
      server:
        native:
          searchLocations: ../local-config-repo
        git:
          uri: git@github.com:MarcialRosales/spring-cloud-workshop-config
          